# Generated by Django 5.0.3 on 2024-08-21 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=6)),
                ('bairro', models.CharField(max_length=60)),
                ('municipio', models.CharField(max_length=60)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso Do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio De Janeiro'), ('RN', 'Rio Grande Do Norte'), ('RS', 'Rio Grande Do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('complemento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('HC', 'Homem cis'), ('HT', 'Homem Trans'), ('MC', 'Mulher cis'), ('MT', 'Mulher trans'), ('AS', 'Assexual'), ('IS', 'Intersex')], max_length=2)),
                ('sexo', models.CharField(choices=[('F', 'FEMININO'), ('M', 'MASCULINO')], max_length=2)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gogus.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=120)),
                ('nome_fantasia', models.EmailField(max_length=100)),
                ('cnpj', models.CharField(max_length=11)),
                ('inscricao_estadual', models.CharField(max_length=9)),
                ('inscricao_municipal', models.CharField(max_length=11)),
                ('contribuinte', models.CharField(choices=[('S', 'SIM'), ('N', 'NAO')], max_length=1)),
                ('status', models.CharField(choices=[('A', 'ATIVO'), ('I', 'INATIVO')], max_length=1)),
                ('contato', models.CharField(max_length=100)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gogus.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_tel', models.CharField(default='+5527999999999', max_length=14)),
                ('tipo_tel', models.CharField(choices=[('MOVEL', 'MOVEL'), ('FIXO', 'FIXO')], default='MOVEL', max_length=5)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
